apiVersion: camel.apache.org/v1alpha1
kind: IntegrationPlatform
metadata:
  name: camel-k
  labels:
    app: "camel-k"
spec:
  build:
    repositories:
    - https://repository.apache.org/content/repositories/snapshots@id=apache.snapshots@snapshots@noreleases
    - https://oss.sonatype.org/content/repositories/snapshots/@id=sonatype.snapshots@snapshots@noreleases
    - https://maven.repository.redhat.com/ga@id=redhat.ga
    - https://origin-repository.jboss.org/nexus/content/groups/ea@id=redhat.ea

