package defaults

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	// Version --
	Version = "0.3.2-summit"

	// CamelVersionConstraint --
	CamelVersionConstraint = "~2.23.x"

	// RuntimeVersion --
	RuntimeVersion = "0.3.2-summit"

	// BaseImage --
	BaseImage = "quay.io/redhatdemo/camel-k-syndesis-base:latest"

	// LocalRepository --
	LocalRepository = "/tmp/artifacts/m2"
)
