package defaults

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	// Version --
	Version = "0.3.2-SNAPSHOT"

	// CamelVersionConstraint --
	CamelVersionConstraint = "3.0.0-M1"

	// RuntimeVersion --
	RuntimeVersion = "0.3.2-SNAPSHOT"

	// BaseImage --
	BaseImage = "fabric8/s2i-java:3.0-java8"

	// LocalRepository --
	LocalRepository = "/tmp/artifacts/m2"
)
